command_timeout = 1000
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

right_format = """$all"""

[os]
disabled = true

[directory]
style = "bold"
format = "[ $path ]($style)"


[custom.giturl]
description = "git url"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output"

[git_branch]
symbol = "[](black) "
# format =  ' [$symbol$branch(:$remote_branch)]($style)[]'
style = "fg:yellow bg:black"
format =  '  on [$symbol$branch]($style)[](black)'

[git_status]
style = "fg:yellow"
format = ' [($all_status$ahead_behind )]($style)'


[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:foam)]($style)'

[line_break]
disabled = true

[character]
disabled = false
